scrapping data from real website + pandas

In [9]:
from bs4 import BeautifulSoup
import requests

In [13]:
url ='https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
headers = {
    "User-Agent": "Mozilla/5.0"
}
page = requests.get(url,headers=headers)

soup =BeautifulSoup(page.text,'html.parser')

In [15]:
print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of largest companies in the United States by revenue - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"e2b5117b-1620-4819-91d8-5c9e2e6a15bc","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgTitle":"List of largest companies in the United States by revenue","wgCurRevisionId":1354288064,"wgRevisionId":1354288064,"wgArticleId":61181662,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use mdy dates from April 2025","Economy of the United States-related lists","Lists of companies by revenue","Lists of largest private companies by country","Lists of companies of the United States"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgRelevantArticleId":61181662,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":30000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Business":{"class":"List","importance":"Low"},"Finance \u0026 Investment":{"class":"List","importance":"Low"},"Lists":{"class":"List","importance":"Low"},"Project-independent assessment":{"class":"List","importance":""},"United States":{"class":"List","importance":"Low"}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q1860802","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.17" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of largest companies in the United States by revenue - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch">
   <link href="auth.wikimedia.org" rel="dns-prefetch"/>
  </link>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_the_United_States_by_revenue rootpage-List_of_largest_companies_in_the_United_States_by_revenue skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2">
           <a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2">

In [19]:
soup.find_all('table')[1]

<table class="wikitable sortable" id="mwBQA">
<tbody id="mwBQE"><tr id="mwBQI"><th id="mwBQM">Rank</th>
<th id="mwBQQ">Name</th>
<th id="mwBQU">Industry</th>
<th id="mwBQY">Revenue <br id="mwBQc"/>(USD billions)</th>
<th id="mwBQg">Employees</th>
<th id="mwBQk">Headquarters</th></tr>
<tr id="mwBQo">
<td id="mwBQs">1</td>
<td id="mwBQw"><a href="https://en.wikipedia.org/wiki/Cargill" id="mwBQ0" rel="mw:WikiLink" title="Cargill">Cargill</a></td>
<td id="mwBQ4">Food &amp; Drink</td>
<td id="mwBQ8" style="text-align:center;">154</td>
<td id="mwBRA" style="text-align:center;">155,000</td>
<td id="mwBRE"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwBRI" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwBRM">
<td id="mwBRQ">2</td>
<td id="mwBRU"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Koch_Industries" id="mwBRY" rel="mw:WikiLink" title="Koch Industries">Koch</a></td>
<td id="mwBRc">Multicompany</td>
<td id="mwBRg" style="text-align:center;">125</td>
<td id="mwBRk" style="text-align:center;">120,000</td>
<td id="mwBRo"><a href="https://en.wikipedia.org/wiki/Wichita,_Kansas" id="mwBRs" rel="mw:WikiLink" title="Wichita, Kansas">Wichita, Kansas</a></td></tr>
<tr id="mwBRw">
<td id="mwBR0">3</td>
<td id="mwBR4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Publix_Super_Markets" id="mwBR8" rel="mw:WikiLink" title="Publix Super Markets">Publix Super Markets</a></td>
<td id="mwBSA">Food Markets</td>
<td id="mwBSE" style="text-align:center;">59.7</td>
<td id="mwBSI" style="text-align:center;">260,000</td>
<td id="mwBSM"><a href="https://en.wikipedia.org/wiki/Lakeland,_Florida" id="mwBSQ" rel="mw:WikiLink" title="Lakeland, Florida">Lakeland, Florida</a></td></tr>
<tr id="mwBSU">
<td id="mwBSY">4</td>
<td id="mwBSc"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Mars,_Incorporated" id="mwBSg" rel="mw:WikiLink" title="Mars, Incorporated">Mars</a></td>
<td id="mwBSk">Food &amp; Drink</td>
<td id="mwBSo" style="text-align:center;">55</td>
<td id="mwBSs" style="text-align:center;">150,000</td>
<td id="mwBSw"><a href="https://en.wikipedia.org/wiki/McLean,_Virginia" id="mwBS0" rel="mw:WikiLink" title="McLean, Virginia">McLean, Virginia</a></td></tr>
<tr id="mwBS4">
<td id="mwBS8">5</td>
<td id="mwBTA"><a href="https://en.wikipedia.org/wiki/H-E-B" id="mwBTE" rel="mw:WikiLink" title="H-E-B">H-E-B Grocery Company</a></td>
<td id="mwBTI">Food Markets</td>
<td id="mwBTM" style="text-align:center;">49.57</td>
<td id="mwBTQ" style="text-align:center;">175,000</td>
<td id="mwBTU"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/San_Antonio,_Texas" id="mwBTY" rel="mw:WikiLink" title="San Antonio, Texas">San Antonio, Texas</a></td></tr>
<tr id="mwBTc">
<td id="mwBTg">6</td>
<td id="mwBTk"><a href="https://en.wikipedia.org/wiki/Reyes_Holdings" id="mwBTo" rel="mw:WikiLink" title="Reyes Holdings">Reyes Holdings</a></td>
<td id="mwBTs">Food, Drink &amp; Tobacco</td>
<td id="mwBTw" style="text-align:center;">44</td>
<td id="mwBT0" style="text-align:center;">36,000</td>
<td id="mwBT4"><a href="https://en.wikipedia.org/wiki/Rosemont,_Illinois" id="mwBT8" rel="mw:WikiLink" title="Rosemont, Illinois">Rosemont, Illinois</a></td></tr>
<tr id="mwBUA">
<td id="mwBUE">7</td>
<td id="mwBUI"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Enterprise_Mobility" id="mwBUM" rel="mw:WikiLink" title="Enterprise Mobility">Enterprise Mobility</a></td>
<td id="mwBUQ">Services</td>
<td id="mwBUU" style="text-align:center;">38</td>
<td id="mwBUY" style="text-align:center;">100,000</td>
<td id="mwBUc"><a href="https://en.wikipedia.org/wiki/Clayton,_Missouri" id="mwBUg" rel="mw:WikiLink" title="Clayton, Missouri">Clayton, Missouri</a></td></tr>
<tr id="mwBUk">
<td id="mwBUo">8</td>
<td id="mwBUs"><a href="https://en.wikipedia.org/wiki/Fidelity_Investments" id="mwBUw" rel="mw:WikiLink" title="Fidelity Investments">Fidelity Investments</a></td>
<td id="mwBU0">Insurance</td>
<td id="mwBU4" style="text-align:center;">32.7</td>
<td id="mwBU8" style="text-align:center;">78,000</td>
<td id="mwBVA"><a href="https://en.wikipedia.org/wiki/Boston" id="mwBVE" rel="mw:WikiLink" title="Boston">Boston, Massachusetts</a></td></tr>
<tr id="mwBVI">
<td id="mwBVM">9</td>
<td id="mwBVQ"><a href="https://en.wikipedia.org/wiki/Southern_Glazer's_Wine_and_Spirits" id="mwBVU" rel="mw:WikiLink" title="Southern Glazer's Wine and Spirits">Southern Glazer's Wine &amp; Spirits</a></td>
<td id="mwBVY">Food, Drink &amp; Tobacco</td>
<td id="mwBVc" style="text-align:center;">25</td>
<td id="mwBVg" style="text-align:center;">24,000</td>
<td id="mwBVk"><a href="https://en.wikipedia.org/wiki/Miramar,_Florida" id="mwBVo" rel="mw:WikiLink" title="Miramar, Florida">Miramar, Florida</a></td></tr>
<tr id="mwBVs">
<td id="mwBVw">10</td>
<td id="mwBV0"><a href="https://en.wikipedia.org/wiki/Cox_Enterprises" id="mwBV4" rel="mw:WikiLink" title="Cox Enterprises">Cox Enterprises</a></td>
<td id="mwBV8">Media</td>
<td id="mwBWA" style="text-align:center;">23.5</td>
<td id="mwBWE" style="text-align:center;">50,000</td>
<td id="mwBWI"><a href="https://en.wikipedia.org/wiki/Atlanta" id="mwBWM" rel="mw:WikiLink" title="Atlanta">Atlanta, Georgia</a></td></tr>
</tbody></table>

In [36]:
table =soup.find_all('table')[0]

In [37]:
soup.find('table',class_='wikitable sortable')

<table class="wikitable sortable" id="mwOw">
<caption id="mwPA"></caption>
<tbody id="mwPQ"><tr id="mwPg"><th id="mwPw">Rank</th>
<th id="mwQA">Name</th>
<th id="mwQQ">Industry</th>
<th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>
<th id="mwRA">Revenue growth</th>
<th id="mwRQ">Employees</th>
<th id="mwRg">Headquarters</th></tr>
<tr id="mwRw">
<td id="mwSA">1</td>
<td id="mwSQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwSg" rel="mw:WikiLink" title="Walmart">Walmart</a></td>
<td id="mwSw">Retail</td>
<td id="mwTA" style="text-align:center;">680,985</td>
<td id="mwTQ" style="text-align:center;"><span about="#mwt7" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwTg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt8" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwTw" style="display:none" typeof="mw:Transclusion"></span> 5.1%</td>
<td id="mwUA" style="text-align:center;">2,100,000</td>
<td id="mwUQ"><a href="https://en.wikipedia.org/wiki/Bentonville,_Arkansas" id="mwUg" rel="mw:WikiLink" title="Bentonville, Arkansas">Bentonville, Arkansas</a></td></tr>
<tr id="mwUw">
<td id="mwVA">2</td>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwVg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td>
<td id="mwVw">Retail and cloud computing</td>
<td id="mwWA" style="text-align:center;">637,959</td>
<td id="mwWQ" style="text-align:center;"><span about="#mwt9" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt10" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwWw" style="display:none" typeof="mw:Transclusion"></span> 11.0%</td>
<td id="mwXA" style="text-align:center;">1,556,000</td>
<td id="mwXQ"><a href="https://en.wikipedia.org/wiki/Seattle" id="mwXg" rel="mw:WikiLink" title="Seattle">Seattle, Washington</a></td></tr>
<tr id="mwXw">
<td id="mwYA">3</td>
<td id="mwYQ"><a href="https://en.wikipedia.org/wiki/UnitedHealth_Group" id="mwYg" rel="mw:WikiLink" title="UnitedHealth Group">UnitedHealth Group</a></td>
<td id="mwYw">Healthcare</td>
<td id="mwZA" style="text-align:center;">400,278</td>
<td id="mwZQ" style="text-align:center;"><span about="#mwt11" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwZg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt12" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwZw" style="display:none" typeof="mw:Transclusion"></span> 7.7%</td>
<td id="mwaA" style="text-align:center;">400,000</td>
<td id="mwaQ"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwag" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwaw">
<td id="mwbA">4</td>
<td id="mwbQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Apple_Inc" id="mwbg" rel="mw:WikiLink" title="Apple Inc">Apple</a></td>
<td id="mwbw">Technology</td>
<td id="mwcA" style="text-align:center;">391,035</td>
<td id="mwcQ" style="text-align:center;"><span about="#mwt13" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwcg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt14" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwcw" style="display:none" typeof="mw:Transclusion"></span> 2.0%</td>
<td id="mwdA" style="text-align:center;">164,000</td>
<td id="mwdQ"><a href="https://en.wikipedia.org/wiki/Cupertino,_California" id="mwdg" rel="mw:WikiLink" title="Cupertino, California">Cupertino, California</a></td></tr>
<tr id="mwdw">
<td id="mweA">5</td>
<td id="mweQ"><a href="https://en.wikipedia.org/wiki/CVS_Health" id="mweg" rel="mw:WikiLink" title="CVS Health">CVS Health</a></td>
<td id="mwew">Healthcare</td>
<td id="mwfA" style="text-align:center;">372,809</td>
<td id="mwfQ" style="text-align:center;"><span about="#mwt15" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwfg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt16" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwfw" style="display:none" typeof="mw:Transclusion"></span> 4.2%</td>
<td id="mwgA" style="text-align:center;">259,500</td>
<td id="mwgQ"><a href="https://en.wikipedia.org/wiki/Woonsocket,_Rhode_Island" id="mwgg" rel="mw:WikiLink" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a></td></tr>
<tr id="mwgw">
<td id="mwhA">6</td>
<td id="mwhQ"><a href="https://en.wikipedia.org/wiki/Berkshire_Hathaway" id="mwhg" rel="mw:WikiLink" title="Berkshire Hathaway">Berkshire Hathaway</a></td>
<td id="mwhw">Conglomerate</td>
<td id="mwiA" style="text-align:center;">371,433</td>
<td id="mwiQ" style="text-align:center;"><span about="#mwt17" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwig" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt18" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwiw" style="display:none" typeof="mw:Transclusion"></span> 1.9%</td>
<td id="mwjA" style="text-align:center;">392,400</td>
<td id="mwjQ"><a href="https://en.wikipedia.org/wiki/Omaha,_Nebraska" id="mwjg" rel="mw:WikiLink" title="Omaha, Nebraska">Omaha, Nebraska</a></td></tr>
<tr id="mwjw">
<td id="mwkA">7</td>
<td id="mwkQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Alphabet_Inc" id="mwkg" rel="mw:WikiLink" title="Alphabet Inc">Alphabet</a></td>
<td id="mwkw">Technology and cloud computing</td>
<td id="mwlA" style="text-align:center;">350,018</td>
<td id="mwlQ" style="text-align:center;"><span about="#mwt19" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwlg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt20" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwlw" style="display:none" typeof="mw:Transclusion"></span> 13.9%</td>
<td id="mwmA" style="text-align:center;">183,323</td>
<td id="mwmQ"><a href="https://en.wikipedia.org/wiki/Mountain_View,_California" id="mwmg" rel="mw:WikiLink" title="Mountain View, California">Mountain View, California</a></td></tr>
<tr id="mwmw">
<td id="mwnA">8</td>
<td id="mwnQ"><a href="https://en.wikipedia.org/wiki/ExxonMobil" id="mwng" rel="mw:WikiLink" title="ExxonMobil">Exxon Mobil</a></td>
<td id="mwnw">Petroleum</td>
<td id="mwoA" style="text-align:center;">349,595</td>
<td id="mwoQ" style="text-align:center;"><span about="#mwt21" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwog" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt22" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwow" style="display:none" typeof="mw:Transclusion"></span> 1.5%</td>
<td id="mwpA" style="text-align:center;">60,900</td>
<td id="mwpQ"><a href="https://en.wikipedia.org/wiki/Spring,_Texas" id="mwpg" rel="mw:WikiLink" title="Spring, Texas">Spring, Texas</a></td></tr>
<tr id="mwpw">
<td id="mwqA">9</td>
<td id="mwqQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/McKesson_Corporation" id="mwqg" rel="mw:WikiLink" title="McKesson Corporation">McKesson Corporation</a></td>
<td id="mwqw">Healthcare</td>
<td id="mwrA" style="text-align:center;">308,951</td>
<td id="mwrQ" style="text-align:center;"><span about="#mwt23" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwrg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt24" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwrw" style="display:none" typeof="mw:Transclusion"></span> 11.7%</td>
<td id="mwsA" style="text-align:center;">48,000</td>
<td id="mwsQ"><a href="https://en.wikipedia.org/wiki/Irving,_Texas" id="mwsg" rel="mw:WikiLink" title="Irving, Texas">Irving, Texas</a></td></tr>
<tr id="mwsw">
<td id="mwtA">10</td>
<td id="mwtQ"><a href="https://en.wikipedia.org/wiki/Cencora" id="mwtg" rel="mw:WikiLink" title="Cencora">Cencora</a></td>
<td id="mwtw">Pharmacy wholesale</td>
<td id="mwuA" style="text-align:center;">293,959</td>
<td id="mwuQ" style="text-align:center;"><span about="#mwt25" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwug" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt26" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwuw" style="display:none" typeof="mw:Transclusion"></span> 12.1%</td>
<td id="mwvA" style="text-align:center;">44,000</td>
<td id="mwvQ"><a href="https://en.wikipedia.org/wiki/Conshohocken,_Pennsylvania" id="mwvg" rel="mw:WikiLink" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a></td></tr>
<tr id="mwvw">
<td id="mwwA">11</td>
<td id="mwwQ"><a href="https://en.wikipedia.org/wiki/JPMorgan_Chase" id="mwwg" rel="mw:WikiLink" title="JPMorgan Chase">JPMorgan Chase</a></td>
<td id="mwww">Financials</td>
<td id="mwxA" style="text-align:center;">278,906</td>
<td id="mwxQ" style="text-align:center;"><span about="#mwt27" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwxg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt28" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwxw" style="display:none" typeof="mw:Transclusion"></span> 16.5%</td>
<td id="mwyA" style="text-align:center;">317,233</td>
<td id="mwyQ"><a href="https://en.wikipedia.org/wiki/New_York_City" id="mwyg" rel="mw:WikiLink" title="New York City">New York City, New York</a></td></tr>
<tr id="mwyw">
<td id="mwzA">12</td>
<td id="mwzQ"><a href="https://en.wikipedia.org/wiki/Costco" id="mwzg" rel="mw:WikiLink" title="Costco">Costco Wholesale</a></td>
<td id="mwzw">Retail</td>
<td id="mw0A" style="text-align:center;">254,453</td>
<td id="mw0Q" style="text-align:center;"><span about="#mwt29" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw0g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt30" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw0w" style="display:none" typeof="mw:Transclusion"></span> 5.0%</td>
<td id="mw1A" style="text-align:center;">333,000</td>
<td id="mw1Q"><a href="https://en.wikipedia.org/wiki/Issaquah,_Washington" id="mw1g" rel="mw:WikiLink" title="Issaquah, Washington">Issaquah, Washington</a></td></tr>
<tr id="mw1w">
<td id="mw2A">13</td>
<td id="mw2Q"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Cigna" id="mw2g" rel="mw:WikiLink" title="Cigna">Cigna</a></td>
<td id="mw2w">Health insurance</td>
<td id="mw3A" style="text-align:center;">247,121</td>

In [38]:
world_titles=table.find_all('th')

In [39]:
world_table_titles =[ title.text.strip() for title in world_titles]

print (world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [40]:
import pandas as pd

In [41]:
df = pd.DataFrame(columns =world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [42]:
column_data =table.find_all('tr')

In [46]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    
    length = len(df)
    df.loc[length] = individual_row_data

In [47]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [49]:
df.to_csv(r'E:\Previous\programming\DA\Python\Companies By Scrapping wiki.csv',index=False)